[default_session]
startup_command = " tmux rename-window hub && tmux set-option -w automatic-rename off && clear"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Dotfiles"
path = "~/.dotfiles"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "Obsidian"
startup_command = "nvim"
path = "~/vaults"
