git:
  overrideGpg: true
  diffRenderers:
    - colorArg: always
      command: delta --paging=never
customCommands:
  - key: "<c-p>"
    command: "git fetch --prune"
    context: "localBranches"
    description: "Prune local branches"
    output: log
